### ISSUE TITLE
Lake bridge 

### ISSUE THREAD

**Issue by williansaez** [GlimmerDev/StardewValleyMod_OmniFarmEx#1]
The bridge appears to be broken, it is passing the limits of the object.

![image](https://github.com/GlimmerDev/StardewValleyMod_OmniFarmEx/assets/23337029/688f0865-30a2-43bb-9633-4ea7e37bde0e)

**Comment by GlimmerDev** [comment]
Thanks for catching this! Fixed in 1.0.4.
